// <auto-generated />
using System;
using LegendsLeague.Infrastructure.Persistence.Fantasy;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LegendsLeague.Infrastructure.Persistence.Fantasy.Migrations
{
    [DbContext(typeof(FantasyDbContext))]
    partial class FantasyDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("fantasy")
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "citext");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LegendsLeague.Domain.Entities.Fantasy.Draft", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<Guid>("LeagueId")
                        .HasColumnType("uuid")
                        .HasColumnName("league_id");

                    b.Property<DateTimeOffset?>("ModifiedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at_utc");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("modified_by");

                    b.Property<DateTimeOffset>("StartsAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("starts_at_utc");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("p_k_drafts");

                    b.HasIndex("LeagueId", "Status")
                        .HasDatabaseName("i_x_drafts_league_id_status");

                    b.ToTable("drafts", "fantasy");
                });

            modelBuilder.Entity("LegendsLeague.Domain.Entities.Fantasy.DraftPick", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<Guid>("DraftId")
                        .HasColumnType("uuid")
                        .HasColumnName("draft_id");

                    b.Property<Guid>("LeagueTeamId")
                        .HasColumnType("uuid")
                        .HasColumnName("league_team_id");

                    b.Property<DateTimeOffset>("MadeAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("made_at_utc");

                    b.Property<DateTimeOffset?>("ModifiedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at_utc");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("modified_by");

                    b.Property<int?>("PickNo")
                        .HasColumnType("integer")
                        .HasColumnName("pick_no");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid")
                        .HasColumnName("player_id");

                    b.Property<int?>("RoundNo")
                        .HasColumnType("integer")
                        .HasColumnName("round_no");

                    b.HasKey("Id")
                        .HasName("p_k_draft_picks");

                    b.HasIndex("LeagueTeamId", "DraftId")
                        .HasDatabaseName("i_x_draft_picks_league_team_id_draft_id");

                    b.HasIndex("DraftId", "RoundNo", "PickNo")
                        .HasDatabaseName("i_x_draft_picks_draft_id_round_no_pick_no");

                    b.ToTable("draft_picks", "fantasy");
                });

            modelBuilder.Entity("LegendsLeague.Domain.Entities.Fantasy.FantasyLeague", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CommissionerUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("commissioner_user_id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<int>("MaxTeams")
                        .HasColumnType("integer")
                        .HasColumnName("max_teams");

                    b.Property<DateTimeOffset?>("ModifiedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at_utc");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("modified_by");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name");

                    b.Property<Guid>("SeriesId")
                        .HasColumnType("uuid")
                        .HasColumnName("series_id");

                    b.HasKey("Id")
                        .HasName("p_k_leagues");

                    b.HasIndex("SeriesId", "Name")
                        .HasDatabaseName("i_x_leagues_series_id_name");

                    b.ToTable("leagues", "fantasy");
                });

            modelBuilder.Entity("LegendsLeague.Domain.Entities.Fantasy.LeagueMember", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("DeletedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at_utc");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("deleted_by");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<DateTimeOffset>("JoinedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("joined_at_utc");

                    b.Property<Guid>("LeagueId")
                        .HasColumnType("uuid")
                        .HasColumnName("league_id");

                    b.Property<DateTimeOffset?>("ModifiedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at_utc");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("modified_by");

                    b.Property<int>("Role")
                        .HasColumnType("integer")
                        .HasColumnName("role");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("p_k_league_members");

                    b.HasIndex("LeagueId", "UserId")
                        .IsUnique()
                        .HasDatabaseName("i_x_league_members_league_id_user_id");

                    b.ToTable("league_members", "fantasy");
                });

            modelBuilder.Entity("LegendsLeague.Domain.Entities.Fantasy.LeagueTeam", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("DeletedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at_utc");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("deleted_by");

                    b.Property<int?>("DraftPosition")
                        .HasColumnType("integer")
                        .HasColumnName("draft_position");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<Guid>("LeagueId")
                        .HasColumnType("uuid")
                        .HasColumnName("league_id");

                    b.Property<DateTimeOffset?>("ModifiedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at_utc");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("modified_by");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("name");

                    b.Property<Guid>("OwnerUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_user_id");

                    b.HasKey("Id")
                        .HasName("p_k_league_teams");

                    b.HasIndex("LeagueId", "Name")
                        .HasDatabaseName("i_x_league_teams_league_id_name");

                    b.HasIndex("LeagueId", "OwnerUserId")
                        .HasDatabaseName("i_x_league_teams_league_id_owner_user_id");

                    b.ToTable("league_teams", "fantasy");
                });

            modelBuilder.Entity("LegendsLeague.Domain.Entities.Fantasy.RosterPlayer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("ActiveFromUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("active_from_utc");

                    b.Property<DateTimeOffset?>("ActiveToUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("active_to_utc");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("DeletedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at_utc");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("deleted_by");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<Guid>("LeagueTeamId")
                        .HasColumnType("uuid")
                        .HasColumnName("league_team_id");

                    b.Property<DateTimeOffset?>("ModifiedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at_utc");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("modified_by");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid")
                        .HasColumnName("player_id");

                    b.Property<int>("Slot")
                        .HasColumnType("integer")
                        .HasColumnName("slot");

                    b.HasKey("Id")
                        .HasName("p_k_roster_players");

                    b.HasIndex("LeagueTeamId", "PlayerId", "Slot")
                        .HasDatabaseName("i_x_roster_players_league_team_id_player_id_slot");

                    b.ToTable("roster_players", "fantasy");
                });

            modelBuilder.Entity("LegendsLeague.Domain.Entities.Fixtures.Fixture", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AwayTeamId")
                        .HasColumnType("uuid")
                        .HasColumnName("away_team_id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("DeletedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at_utc");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("deleted_by");

                    b.Property<Guid>("HomeTeamId")
                        .HasColumnType("uuid")
                        .HasColumnName("home_team_id");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<DateTimeOffset?>("ModifiedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at_utc");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("modified_by");

                    b.Property<Guid>("SeriesId")
                        .HasColumnType("uuid")
                        .HasColumnName("series_id");

                    b.Property<DateTimeOffset>("StartTimeUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_time_utc");

                    b.HasKey("Id")
                        .HasName("p_k_fixtures");

                    b.HasIndex("AwayTeamId")
                        .HasDatabaseName("i_x_fixtures_away_team_id");

                    b.HasIndex("HomeTeamId")
                        .HasDatabaseName("i_x_fixtures_home_team_id");

                    b.HasIndex("SeriesId")
                        .HasDatabaseName("i_x_fixtures_series_id");

                    b.ToTable("fixtures", "fantasy");
                });

            modelBuilder.Entity("LegendsLeague.Domain.Entities.Fixtures.Player", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Batting")
                        .HasColumnType("integer")
                        .HasColumnName("batting");

                    b.Property<int>("Bowling")
                        .HasColumnType("integer")
                        .HasColumnName("bowling");

                    b.Property<string>("Country")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("country");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("DeletedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at_utc");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("deleted_by");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("full_name");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<DateTimeOffset?>("ModifiedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at_utc");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("modified_by");

                    b.Property<Guid>("RealTeamId")
                        .HasColumnType("uuid")
                        .HasColumnName("real_team_id");

                    b.Property<int>("Role")
                        .HasColumnType("integer")
                        .HasColumnName("role");

                    b.Property<Guid>("SeriesId")
                        .HasColumnType("uuid")
                        .HasColumnName("series_id");

                    b.Property<string>("ShortName")
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("short_name");

                    b.HasKey("Id")
                        .HasName("p_k_players");

                    b.HasIndex("FullName")
                        .HasDatabaseName("ix_players_full_name");

                    b.HasIndex("RealTeamId")
                        .HasDatabaseName("i_x_players_real_team_id");

                    b.HasIndex("SeriesId", "RealTeamId")
                        .HasDatabaseName("ix_players_seriesid_teamid");

                    b.ToTable("players", "fantasy");
                });

            modelBuilder.Entity("LegendsLeague.Domain.Entities.Fixtures.RealTeam", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("DeletedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at_utc");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("deleted_by");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<DateTimeOffset?>("ModifiedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at_utc");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("modified_by");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name");

                    b.Property<Guid>("SeriesId")
                        .HasColumnType("uuid")
                        .HasColumnName("series_id");

                    b.Property<string>("ShortName")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("short_name");

                    b.HasKey("Id")
                        .HasName("p_k_real_teams");

                    b.HasIndex("SeriesId")
                        .HasDatabaseName("i_x_real_teams_series_id");

                    b.ToTable("real_teams", "fantasy");
                });

            modelBuilder.Entity("LegendsLeague.Domain.Entities.Fixtures.Series", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("ModifiedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at_utc");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("modified_by");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("citext")
                        .HasColumnName("name");

                    b.Property<int>("SeasonYear")
                        .HasColumnType("integer")
                        .HasColumnName("season_year");

                    b.HasKey("Id")
                        .HasName("p_k_series");

                    b.HasIndex("SeasonYear", "Name")
                        .IsUnique()
                        .HasDatabaseName("ux_series_season_year_name");

                    b.ToTable("series", "fantasy");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            CreatedAtUtc = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "Indian Premier League",
                            SeasonYear = 2026
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            CreatedAtUtc = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "ICC T20 World Cup",
                            SeasonYear = 2026
                        });
                });

            modelBuilder.Entity("LegendsLeague.Domain.Entities.Fantasy.Draft", b =>
                {
                    b.HasOne("LegendsLeague.Domain.Entities.Fantasy.FantasyLeague", "League")
                        .WithMany("Drafts")
                        .HasForeignKey("LeagueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_drafts_leagues_league_id");

                    b.Navigation("League");
                });

            modelBuilder.Entity("LegendsLeague.Domain.Entities.Fantasy.DraftPick", b =>
                {
                    b.HasOne("LegendsLeague.Domain.Entities.Fantasy.Draft", "Draft")
                        .WithMany("Picks")
                        .HasForeignKey("DraftId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_draft_picks_drafts_draft_id");

                    b.HasOne("LegendsLeague.Domain.Entities.Fantasy.LeagueTeam", "LeagueTeam")
                        .WithMany()
                        .HasForeignKey("LeagueTeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_draft_picks_league_teams_league_team_id");

                    b.Navigation("Draft");

                    b.Navigation("LeagueTeam");
                });

            modelBuilder.Entity("LegendsLeague.Domain.Entities.Fantasy.LeagueMember", b =>
                {
                    b.HasOne("LegendsLeague.Domain.Entities.Fantasy.FantasyLeague", "League")
                        .WithMany("Members")
                        .HasForeignKey("LeagueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_league_members_leagues_league_id");

                    b.Navigation("League");
                });

            modelBuilder.Entity("LegendsLeague.Domain.Entities.Fantasy.LeagueTeam", b =>
                {
                    b.HasOne("LegendsLeague.Domain.Entities.Fantasy.FantasyLeague", "League")
                        .WithMany("Teams")
                        .HasForeignKey("LeagueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_league_teams_leagues_league_id");

                    b.Navigation("League");
                });

            modelBuilder.Entity("LegendsLeague.Domain.Entities.Fantasy.RosterPlayer", b =>
                {
                    b.HasOne("LegendsLeague.Domain.Entities.Fantasy.LeagueTeam", "LeagueTeam")
                        .WithMany("Roster")
                        .HasForeignKey("LeagueTeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_roster_players_league_teams_league_team_id");

                    b.Navigation("LeagueTeam");
                });

            modelBuilder.Entity("LegendsLeague.Domain.Entities.Fixtures.Fixture", b =>
                {
                    b.HasOne("LegendsLeague.Domain.Entities.Fixtures.RealTeam", "AwayTeam")
                        .WithMany()
                        .HasForeignKey("AwayTeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("f_k_fixtures_real_teams_away_team_id");

                    b.HasOne("LegendsLeague.Domain.Entities.Fixtures.RealTeam", "HomeTeam")
                        .WithMany()
                        .HasForeignKey("HomeTeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("f_k_fixtures_real_teams_home_team_id");

                    b.HasOne("LegendsLeague.Domain.Entities.Fixtures.Series", "Series")
                        .WithMany("Fixtures")
                        .HasForeignKey("SeriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_fixtures_series_series_id");

                    b.Navigation("AwayTeam");

                    b.Navigation("HomeTeam");

                    b.Navigation("Series");
                });

            modelBuilder.Entity("LegendsLeague.Domain.Entities.Fixtures.Player", b =>
                {
                    b.HasOne("LegendsLeague.Domain.Entities.Fixtures.RealTeam", "RealTeam")
                        .WithMany()
                        .HasForeignKey("RealTeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("f_k_players_real_teams_real_team_id");

                    b.HasOne("LegendsLeague.Domain.Entities.Fixtures.Series", "Series")
                        .WithMany()
                        .HasForeignKey("SeriesId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("f_k_players_series_series_id");

                    b.Navigation("RealTeam");

                    b.Navigation("Series");
                });

            modelBuilder.Entity("LegendsLeague.Domain.Entities.Fixtures.RealTeam", b =>
                {
                    b.HasOne("LegendsLeague.Domain.Entities.Fixtures.Series", "Series")
                        .WithMany("RealTeams")
                        .HasForeignKey("SeriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_real_teams_series_series_id");

                    b.Navigation("Series");
                });

            modelBuilder.Entity("LegendsLeague.Domain.Entities.Fantasy.Draft", b =>
                {
                    b.Navigation("Picks");
                });

            modelBuilder.Entity("LegendsLeague.Domain.Entities.Fantasy.FantasyLeague", b =>
                {
                    b.Navigation("Drafts");

                    b.Navigation("Members");

                    b.Navigation("Teams");
                });

            modelBuilder.Entity("LegendsLeague.Domain.Entities.Fantasy.LeagueTeam", b =>
                {
                    b.Navigation("Roster");
                });

            modelBuilder.Entity("LegendsLeague.Domain.Entities.Fixtures.Series", b =>
                {
                    b.Navigation("Fixtures");

                    b.Navigation("RealTeams");
                });
#pragma warning restore 612, 618
        }
    }
}
